package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.FoodMyBatis;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon Apr 20 11:49:29 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon Apr 20 11:49:29 EEST 2020
     */
    int insert(FoodMyBatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon Apr 20 11:49:29 EEST 2020
     */
    FoodMyBatis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon Apr 20 11:49:29 EEST 2020
     */
    List<FoodMyBatis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon Apr 20 11:49:29 EEST 2020
     */
    int updateByPrimaryKey(FoodMyBatis record);
}